# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd

healthcare_dataset=pd.read_csv("/content/healthcare_dataset.csv")
healthcare_dataset



